modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Grindstone%20Sharper%20Tools"
logoFile="icon.png"

[[mods]]
modId="grindstonesharpertools"
version="3.7"
displayName="Grindstone Sharper Tools"
displayURL="https://serilum.com/mod/grindstone-sharper-tools"
authors="Rick South"
description='''The grindstone can sharpen tools, temporarily increasing their damage dealt.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.grindstonesharpertools]]
    modId="collective"
    mandatory=true
    versionRange="[7.86,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grindstonesharpertools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"
